
echo "Mampus Semua File Lu Hilang"
echo "Roni suka colmek"
echo "tadi gw ngecrot mama gw"
echo "nama gw roni"
echo "gw suka coli"
echo "gw coli di wc umum setiap hari"
echo "karena gw gk punya wc"
echo "gw roni telcakiti"
echo "tadi gw di marahin mama gw,terus mama gw ge entod"
echo "mama gw desahannya mantap bro"
echo "gw broken home,setiap hari dimarahin mama gw"
